Added filtering by author and optimized slider
silevis/internships-2021 pull request #154
Opened 2021-07-29 12:23 UTC by Maximover

2021-07-29 12:30 UTC, wps0 requested changes

2021-07-29 12:30 UTC, wps0 commented on src/components/Sidebar.tsx
> +              /><br />
brr

2021-07-29 12:30 UTC, wps0 commented on src/views/BookListView.tsx
> +const checkAuthors = (authors: string[], query: string) => {
I suggest renaming this function so that it is more self-descriptive.

2021-07-29 12:30 UTC, wps0 commented on src/views/BookListView.tsx
> +      } else if (getFilterType() === 'authors') {
With such a setup, there's no possibility of filtering by both an author and book rating.

2021-07-29 12:38 UTC, wps0 approved these changes

2021-07-30 06:27 UTC, painTojn1 approved these changes

2021-07-30 06:52 UTC, merged